### ISSUE TITLE
installing pytorch binding

### ISSUE THREAD

**Issue by mohamad-hasan-sohan-ajini** [SeanNaren/warp-ctc#76]
Hi

I get the following error while installing pytorch binding (`sudo python setup.py install`):

> generating build/warpctc_pytorch/_warp_ctc/__warp_ctc.c
(already up-to-date)
not modified: 'build/warpctc_pytorch/_warp_ctc/__warp_ctc.c'
running install
running bdist_egg
running egg_info
writing warpctc_pytorch.egg-info/PKG-INFO
writing top-level names to warpctc_pytorch.egg-info/top_level.txt
writing dependency_links to warpctc_pytorch.egg-info/dependency_links.txt
reading manifest file 'warpctc_pytorch.egg-info/SOURCES.txt'
writing manifest file 'warpctc_pytorch.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying warpctc_pytorch/_warp_ctc/__init__.py -> build/lib.linux-x86_64-2.7/warpctc_pytorch/_warp_ctc
running build_ext
building 'warpctc_pytorch._warp_ctc.__warp_ctc' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/sobhe/repo/warp-ctc/include -I/usr/include/python2.7 -c build/warpctc_pytorch/_warp_ctc/__warp_ctc.c -o build/temp.linux-x86_64-2.7/build/warpctc_pytorch/_warp_ctc/__warp_ctc.o -std=c++11 -fPIC -std=c99 -DWARPCTC_ENABLE_GPU
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/sobhe/repo/warp-ctc/include -I/usr/include/python2.7 -c /home/sobhe/repo/warp-ctc/pytorch_binding/src/binding.cpp -o build/temp.linux-x86_64-2.7/home/sobhe/repo/warp-ctc/pytorch_binding/src/binding.o -std=c++11 -fPIC -std=c99 -DWARPCTC_ENABLE_GPU
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-std=c99’ is valid for C/ObjC but not for C++
/home/sobhe/repo/warp-ctc/pytorch_binding/src/binding.cpp: In function ‘int gpu_ctc(THCudaTensor*, THCudaTensor*, THIntTensor*, THIntTensor*, THIntTensor*, int, THFloatTensor*, int)’:
/home/sobhe/repo/warp-ctc/pytorch_binding/src/binding.cpp:92:49: error: cannot convert ‘THCudaTensor*’ to ‘const THFloatTensor*’ for argument ‘1’ to ‘int64_t THFloatTensor_size(const THFloatTensor*, int)’
     int probs_size = THFloatTensor_size(probs, 2);
                                                 ^
/home/sobhe/repo/warp-ctc/pytorch_binding/src/binding.cpp:105:61: error: invalid conversion from ‘size_t {aka long unsigned int}’ to ‘void**’ [-fpermissive]
     void* gpu_workspace = THCudaMalloc(state, gpu_size_bytes);
                                                             ^
/home/sobhe/repo/warp-ctc/pytorch_binding/src/binding.cpp:105:61: error: too few arguments to function ‘cudaError_t THCudaMalloc(THCState*, void**, size_t)’
In file included from /usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from /home/sobhe/repo/warp-ctc/pytorch_binding/src/binding.cpp:9:
/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:209:21: note: declared here
 THC_API cudaError_t THCudaMalloc(THCState *state, void **ptr, size_t size);
                     ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Please help me with this error.

P.S. I get the same error with either gcc-4.8 or gcc-5.4 & CUDA 8.0

**Comment by jielingTang** [comment]
i  have the  same problem. Do you have  resolve it?
i  only modify a  little at "pytorch_binding/src/binding.cpp" ,it  compile success:
    1 at 92 line
        int probs_size = THCudaTensor_size(state, probs, 2);
     2 at l05 lines 
        void* gpu_workspace;
        THCudaMalloc(state, &gpu_workspace, gpu_size_bytes);
good luck to you!

**Comment by zwenwang** [comment]
I reinstall the pytorch and it works.
I installed pytorch 0.4.1 before and had the same problem as you, but now I install pytorch 0.4.0 and it compile success.
I use python 2.7 and cuda 8.0

**Comment by mohamad-hasan-sohan-ajini** [comment]
@jielingTang Thanks a lot man! It worked like a charm.

@zwenwang I used exactly the same configuration as you mentioned, but there was no success to compile! Thanks a lot btw.

@SeanNaren should these solutions mentioned by jielingTang added to repo?

**Comment by Tangent-Wei** [comment]
@zwenwang It work for me. thanks god!

**Comment by the-butterfly** [comment]
@jielingTang 
I just get the same answer for few hours. 
What a pity for not seeing your answer earlier.
Anyway, thanks a lot.

**Comment by tailongnguyen** [comment]
@jielingTang I tried your solution but it does not fix the error. 
```
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-std=c99’ is valid for C/ObjC but not for C++ [enabled by default]
/home/tailongnguyen/deep-anpr/warp-ctc/pytorch_binding/src/binding.cpp: In function ‘int gpu_ctc(THCudaTensor*, THCudaTensor*, THIntTensor*, THIntTensor*, THIntTensor*, int, THFloatTensor*, int)’:
/home/tailongnguyen/deep-anpr/warp-ctc/pytorch_binding/src/binding.cpp:92:48: error: cannot convert ‘THCudaTensor*’ to ‘THCState*’ for argument ‘1’ to ‘int64_t THCudaTensor_size(THCState*, const THCudaTensor*, int)’
     int probs_size = THCudaTensor_size(probs, 2);
                                                ^
/home/tailongnguyen/deep-anpr/warp-ctc/pytorch_binding/src/binding.cpp:105:77: error: cannot convert ‘cudaError_t {aka cudaError}’ to ‘void*’ in initialization
     void* gpu_workspace = THCudaMalloc(state, &gpu_workspace, gpu_size_bytes);
                                                                             ^
error: command 'gcc' failed with exit status 1
```
Any suggestion please?

**Comment by the-butterfly** [comment]
@tailongnguyen Please reread the answer carefully !

**Comment by cyh1112** [comment]
@jielingTang  Thanks a lot,  It's amazing.

**Comment by chenjun2hao** [comment]
@jielingTang ,perfect!

**Comment by mankeyboy** [comment]
Running the speech_recognition code in https://github.com/mlperf/reference/tree/master/speech_recognition which uses warp-ctc and DeepSpeech fails with a CUDA out of memory error in THCachingAllocator if built with the fixes mentioned above for Python 2.7 with PyTorch 0.4.0 or 0.4.1:

This output is for ```run_and_time.sh``` in https://github.com/mlperf/reference/tree/master/speech_recognition/pytorch:
```
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "ppc64le-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/mlperf/anaconda2/envs/pytorch_py36/bin/python3.6...done.
Starting program: /home/mlperf/anaconda2/envs/pytorch_py36/bin/python train.py --model_path models/deepspeech_t1.pth.tar --seed 1 --acc 23
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Detaching after fork from child process 95493.
Detaching after fork from child process 95505.
Detaching after fork from child process 95506.
=======================================================
***checkpoint                = False 
***save_folder               = models/ 
***model_path                = models/deepspeech_t1.pth.tar 
***continue_from             =  
***seed                      = 1 
***acc                       = 23.0 
***start_epoch               = -1 
=======================================================
Directory already exists.
DataParallel(
  (module): DeepSpeech(
    (conv): Sequential(
      (0): Conv2d(1, 32, kernel_size=(41, 11), stride=(2, 2))
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): Hardtanh(min_val=0, max_val=20, inplace)
      (3): Conv2d(32, 32, kernel_size=(21, 11), stride=(2, 1))
      (4): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): Hardtanh(min_val=0, max_val=20, inplace)
    )
    (rnns): Sequential(
      (0): BatchRNN(
        (rnn): GRU(672, 2560)
      )
      (1): BatchRNN(
        (rnn): GRU(2560, 2560)
      )
      (2): BatchRNN(
        (rnn): GRU(2560, 2560)
      )
    )
    (fc): Sequential(
      (0): SequenceWise (
      Sequential(
        (0): BatchNorm1d(2560, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (1): Linear(in_features=2560, out_features=29, bias=False)
      ))
    )
    (inference_log_softmax): InferenceBatchLogSoftmax()
  )
)
Number of parameters: 103841568
Detaching after fork from child process 95529.
terminate called after throwing an instance of 'at::Error'
  what():  CUDA error: out of memory (allocate at /home/builder/build/pytorch/rpmbuild/BUILD/pytorch/aten/src/THC/THCCachingAllocator.cpp:510)
frame #0: THCudaMalloc + 0xc4 (0x7fffc88e9184 in /opt/DL/pytorch/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #1: gpu_ctc + 0x174 (0x7fff92b32894 in /home/mlperf/anaconda2/envs/pytorch_py36/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-linux-ppc64le.egg/warpctc_pytorch/_warp_ctc/__warp_ctc.cpython-36m-powerpc64le-linux-gnu.so)
frame #2: <unknown function> + 0x1d74 (0x7fff92b31d74 in /home/mlperf/anaconda2/envs/pytorch_py36/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-linux-ppc64le.egg/warpctc_pytorch/_warp_ctc/__warp_ctc.cpython-36m-powerpc64le-linux-gnu.so)
frame #3: PyCFunction_Call + 0x1a4 (0x1000d70a4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #4: PyObject_Call + 0x74 (0x1000d1bb4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #5: THPModule_safeCall(_object*, _object*, _object*) + 0x78 (0x7fffec393ff8 in /opt/DL/pytorch/lib/python3.6/site-packages/torch/_C.cpython-36m-powerpc64le-linux-gnu.so)
frame #6: PyCFunction_Call + 0x148 (0x1000d7048 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #7: _PyEval_EvalFrameDefault + 0x739c (0x10020075c in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #8: PyEval_EvalFrameEx + 0x34 (0x1000ae4d4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #9: <unknown function> + 0x1b15c8 (0x1001b15c8 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #10: <unknown function> + 0x1b2cd4 (0x1001b2cd4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #11: <unknown function> + 0x1bce9c (0x1001bce9c in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x604 (0x1001f99c4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #13: PyEval_EvalFrameEx + 0x34 (0x1000ae4d4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #14: PyEval_EvalCodeEx + 0x364 (0x1001b3dc4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #15: <unknown function> + 0x1b5a60 (0x1001b5a60 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #16: PyObject_Call + 0x74 (0x1000d1bb4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #17: PyEval_CallObjectWithKeywords + 0x3c (0x1000d89bc in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #18: PyObject_CallObject + 0x1c (0x1000d8a9c in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #19: THPFunction_apply(_object*, _object*) + 0x410 (0x7fffec883df0 in /opt/DL/pytorch/lib/python3.6/site-packages/torch/_C.cpython-36m-powerpc64le-linux-gnu.so)
frame #20: _PyCFunction_FastCallDict + 0xb0 (0x1000d1de0 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #21: _PyCFunction_FastCallKeywords + 0x24 (0x10011fec4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #22: <unknown function> + 0x1bcd1c (0x1001bcd1c in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #23: _PyEval_EvalFrameDefault + 0x604 (0x1001f99c4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #24: PyEval_EvalFrameEx + 0x34 (0x1000ae4d4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #25: _PyFunction_FastCallDict + 0x16c (0x1001b35cc in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #26: _PyObject_FastCallDict + 0x2fc (0x1000d244c in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #27: _PyObject_Call_Prepend + 0x88 (0x1000db388 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #28: <unknown function> + 0xdb4b4 (0x1000db4b4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #29: PyObject_Call + 0x74 (0x1000d1bb4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #30: _PyEval_EvalFrameDefault + 0x2224 (0x1001fb5e4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #31: PyEval_EvalFrameEx + 0x34 (0x1000ae4d4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #32: <unknown function> + 0x1b1068 (0x1001b1068 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #33: _PyFunction_FastCallDict + 0x27c (0x1001b36dc in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #34: _PyObject_FastCallDict + 0x2fc (0x1000d244c in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #35: _PyObject_Call_Prepend + 0x88 (0x1000db388 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #36: <unknown function> + 0xdb4b4 (0x1000db4b4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #37: PyObject_Call + 0x74 (0x1000d1bb4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #38: <unknown function> + 0x174dfc (0x100174dfc in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #39: _PyObject_FastCallDict + 0xcc (0x1000d221c in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #40: _PyObject_FastCallKeywords + 0x60 (0x1001b3320 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #41: <unknown function> + 0x1bcf60 (0x1001bcf60 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #42: _PyEval_EvalFrameDefault + 0x604 (0x1001f99c4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #43: PyEval_EvalFrameEx + 0x34 (0x1000ae4d4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #44: <unknown function> + 0x1b27fc (0x1001b27fc in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #45: <unknown function> + 0x1bce9c (0x1001bce9c in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #46: _PyEval_EvalFrameDefault + 0x604 (0x1001f99c4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #47: PyEval_EvalFrameEx + 0x34 (0x1000ae4d4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #48: PyEval_EvalCodeEx + 0x364 (0x1001b3dc4 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #49: PyEval_EvalCode + 0x3c (0x1001b591c in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #50: <unknown function> + 0x2b4700 (0x1002b4700 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #51: PyRun_FileExFlags + 0xd8 (0x1002b4d98 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #52: PyRun_SimpleFileExFlags + 0x210 (0x1002b5090 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #53: PyRun_AnyFileExFlags + 0x64 (0x1002b5504 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #54: Py_Main + 0xa98 (0x1002bbfe8 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #55: main + 0x140 (0x100086b80 in /home/mlperf/anaconda2/envs/pytorch_py36/bin/python)
frame #56: <unknown function> + 0x25100 (0x7ffff7d65100 in /lib64/libc.so.6)
frame #57: __libc_start_main + 0xc4 (0x7ffff7d652f4 in /lib64/libc.so.6)

[New Thread 0x7fff89c4f1b0 (LWP 95517)]
[New Thread 0x7fff8943f1b0 (LWP 95518)]
[New Thread 0x7fff8afbf1b0 (LWP 95530)]

Program received signal SIGABRT, Aborted.
0x00007ffff7d7faf0 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.ppc64le gsm-1.0.13-11.el7.ppc64le libpng-1.5.13-7.el7_2.ppc64le libtool-ltdl-2.4.2-22.el7_3.ppc64le libuuid-2.23.2-52.el7.ppc64le sox-14.4.1-6.el7.ppc64le
(gdb) bt
#0  0x00007ffff7d7faf0 in raise () from /lib64/libc.so.6
#1  0x00007ffff7d81e6c in abort () from /lib64/libc.so.6
#2  0x00007fffc339bbec in __gnu_cxx::__verbose_terminate_handler ()
    at /opt/conda/conda-bld/compilers_linux-ppc64le_1534514780560/work/.build/powerpc64le-conda_cos7-linux-gnu/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007fffc3398f8c in __cxxabiv1::__terminate (handler=<optimized out>)
    at /opt/conda/conda-bld/compilers_linux-ppc64le_1534514780560/work/.build/powerpc64le-conda_cos7-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007fffc3399038 in std::terminate ()
    at /opt/conda/conda-bld/compilers_linux-ppc64le_1534514780560/work/.build/powerpc64le-conda_cos7-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007fffc3399444 in __cxxabiv1::__cxa_throw (obj=<optimized out>, 
    tinfo=0x7fffed4cc508 <typeinfo for at::Error>, dest=0x7fffc864f410 <at::Error::~Error()>)
    at /opt/conda/conda-bld/compilers_linux-ppc64le_1534514780560/work/.build/powerpc64le-conda_cos7-linux-gnu/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007fffc88e1ee4 in CudaCachingAllocator::allocate(unsigned long) const ()
   from /opt/DL/pytorch/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so
#7  0x00007fffc88e9184 in THCudaMalloc () from /opt/DL/pytorch/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so
#8  0x00007fff92b32894 in gpu_ctc (probs=<optimized out>, grads=<optimized out>, labels=<optimized out>, 
    label_sizes=<optimized out>, sizes=0x101f137c0, minibatch_size=<optimized out>, costs=<optimized out>, 
    blank_label=<optimized out>) at /home/mlperf/mlperf/warp-ctc/pytorch_binding/src/binding.cpp:106
#9  0x00007fff92b31d74 in _cffi_f_gpu_ctc (self=<optimized out>, args=<optimized out>)
    at build/warpctc_pytorch/_warp_ctc/__warp_ctc.c:792
#10 0x00000001000d70a4 in PyCFunction_Call ()
#11 0x00000001000d1bb4 in PyObject_Call ()
#12 0x00007fffec393ff8 in THPModule_safeCall (_unused=<optimized out>, args=0x1003bf560 <_PyThreadState_Current>, 
    kwargs=0x7fff92b6cf30) at torch/csrc/Module.cpp:182
#13 0x00000001000d7048 in PyCFunction_Call ()
#14 0x000000010020075c in _PyEval_EvalFrameDefault ()
#15 0x00000001000ae4d4 in PyEval_EvalFrameEx ()
#16 0x00000001001b15c8 in _PyEval_EvalCodeWithName ()
#17 0x00000001001b2cd4 in fast_function ()
Backtrace stopped: frame did not save the PC
(gdb) quit
A debugging session is active.

  Inferior 1 [process 95490] will be killed.

Quit anyway? (y or n) y

real  1m25.072s
user  0m8.555s
sys 0m1.057s

```
I had to rebuild everything with Python 3.6 and even without the modification suggested above, the code was able to run and execute without errors with PyTorch 0.4.0 and 0.4.1

**Comment by struCoder** [comment]
@jielingTang 
amazing...

**Comment by abuvaneswari** [comment]
With PyTorch 0.4.0, gcc 4.9, @jielingTang 's fix is MUCH NEEDED. Works fine afterward.
With PyTorch 0.4.1, gcc 4.9, @jielingTang 's fix is NOT NEEDED. Works fine.

**Comment by kevgeo** [comment]
@tailongnguyen Hi, even I got the same error with python 3.6 and cuda 8.0. Have you been able to solve it?

**Comment by sdzbft** [comment]
> i have the same problem. Do you have resolve it?
> i only modify a little at "pytorch_binding/src/binding.cpp" ,it compile success:
> 1 at 92 line
> int probs_size = THCudaTensor_size(state, probs, 2);
> 2 at l05 lines
> void* gpu_workspace;
> THCudaMalloc(state, &gpu_workspace, gpu_size_bytes);
> good luck to you!
thx alot, It works!!!!
